image: python:3.11-slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/uv"

cache:
  paths:
    - .cache/pip
    - .cache/uv

before_script:
  - pip install uv
  - uv venv .venv
  - source .venv/bin/activate
  - uv pip install . # Tai 'uv pip install -r pyproject.toml'

stages:
  - lint
  - test

# Tarkistetaan koodin laatu (Pylint)
linting:
  stage: lint
  script:
    - uv pip install pylint
    - pylint main.py app.py agentti/crew.py --fail-under=5.0
  allow_failure: true

# Suoritetaan varsinaiset testit
unit_tests:
  stage: test
  script:
    - uv pip install pytest pytest-mock pandas duckdb pyarrow
    - coverage run -m pytest tests/
    - coverage report -m
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml